### ISSUE TITLE
Would be nicer if the google fonts could be stored localy and be loaded from there.

### ISSUE THREAD

**Issue by mojtaba-esk** [Waziup/wazigate-dashboard#4]
Would be nicer if the google fonts could be stored localy and be loaded from there.

**Comment by j-forster** [comment]
Fonts are selected based on the operating system and have some fallbacks as default, see https://github.com/Waziup/wazigate-dashboard/blob/master/src/style/index.scss#L5-L46.
There are no fonts loaded from any remote server.
